apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kpring
spec:
  generators:
    - list:
        elements:
          - cluster: kpring
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-application-msa'
    spec:
      syncPolicy:
        automated: { }
      project: default
      source:
        repoURL: https://github.com/kSideProject/kpring-infra.git
        targetRevision: HEAD
        path: .
      destination:
        server: '{{url}}'
        namespace: dev
