apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: swagger
spec:
  generators:
    - list:
        elements:
          - cluster: kpring
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-swagger'
    spec:
      project: default
      source:
        repoURL: https://github.com/kSideProject/kpring-service-mesh.git
        targetRevision: HEAD
        path: swagger
      destination:
        server: '{{url}}'
        namespace: swagger