enabled: true

name: swagger

service:
  port: 80

image:
  repository: swaggerapi/swagger-ui
  tag: latest

env:
  - name: BASE_URL
    value: "/swagger"
  - name: URLS
    value: "[{name: 'auth', url: 'https://kpring.duckdns.org/auth/static/openapi3.yaml'},{name: 'user', url: 'https://kpring.duckdns.org/user/static/openapi3.yaml'}, {name: 'server', url: 'https://kpring.duckdns.org/server/static/openapi3.yaml'}]"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: kpring.duckdns.org
      paths:
        - path: /swagger
          pathType: Prefix
          name: swagger
  tls:
    - hosts:
        - kpring.duckdns.org
      secretName: letsencrypt-prod-tls
