apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.namespace | default }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}